---
- hosts: all
  tasks:
    - name: Print message
      debug:
        msg: Commit in Master branch      
   
    - name: Print message
      debug:
        msg: Commit in feature-2 branch
       
    - name: Print message
      debug:
        msg: Commit in feature-1 branch    
        
    - name: Print message
      debug:
        msg: Commit in feature-4 branch
